#!/usr/bin/env bash

BASEDIR=$(dirname $0)
cd $BASEDIR

source .env

# --------------------------------------------------------------
# Get destination.
# --------------------------------------------------------------

if [ "$1" ]; then
  # Use the first argument as destination if provided.
  DESTINATION=$1
else
  # Look for a variable provided in the .env file.
  DESTINATION="$SERVER_NAME"
fi

# Try if it exists.
if [ -z "$DESTINATION" ]; then
  echo "Error: no destination provided (as .env variable or argument)."
  exit 1
fi

echo "Deploying to '$DESTINATION'…"

# --------------------------------------------------------------
# Deploy.
# --------------------------------------------------------------

echo 'Creating latest build…'

yarn run export

echo 'Syncing…'

# Trailing slash after out is important!
# It means it won't copy the folder, but its content,
# allowing us to have a different name from
# the source (`out`) and the target (`steredenn`).
rsync -vaz out/ $DESTINATION:/var/www/steredenn

ssh $DESTINATION 'service nginx restart'

echo 'Cleaning…'

# Clean.
rm -rf out

echo 'Done.'
