#!/usr/bin/env bash

DESTINATION=$1

if [ -z "$DESTINATION" ]; then
  echo "Error: no user@server argument. Abort..."
  exit 0
fi

yarn run export

# Trailing slash after out is important!
# It means it won't copy the folder, but its content,
# allowing us to have a different name from
# the source (`out`) and the target (`steredenn`).
rsync -vaz out/ $DESTINATION:/var/www/steredenn

ssh $DESTINATION 'service nginx restart'

# Clean.
rm -rf out
