server {
  listen 80;
  server_name steredenn.pixelnest.io;

  # Logs.
  access_log /var/log/www/steredenn-access.log;
  error_log /var/log/www/steredenn-error.log notice;

  # Errors.
  error_page 404 /404/index.html;

  location '/' {
    root /var/www/steredenn;
    index index.html;
  }

  # Compatibility with old website:

  location '/classic' {
    alias /var/www/steredenn-classic;
  }

  location '/public' {
    alias /var/www/steredenn-classic/public;
  }

  location '/bigbang' {
    alias /var/www/steredenn-classic/bigbang;
  }

  location '/help/xbox' {
    alias /var/www/steredenn-classic/help/xbox;
  }
}
